name: Build Release Android

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Release AAB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Build Script for android
        run: ./build.sh -r
      
      - uses: r0adkll/sign-android-release@v1
        name: Sign Android app AAB
        id: sign_app
        with:
          releaseDirectory: platforms/android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.NAIRELAND_KEYSTORE }}
          alias: alias_name
          keyStorePassword: ${{ secrets.NAIRELAND_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.NAIRELAND_KEYSTORE_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "30.0.3"

      - name: Upload release bundle
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: platforms/android/app/build/outputs/bundle/release/app-release.aab